parameters:
#    foment_gestio.example.class: Foment\GestioBundle\Example

services:
#    foment_gestio.example:
#        class: %foment_gestio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
